### ISSUE TITLE
why use multiple threads to execute the function "batch_and_learn" in dmc.py.

### ISSUE THREAD

**Issue by huzhoudaxia** [kwai/DouZero#21]
In douzero.dmc.dmc, about line 168 to line 174, why use multiple threads to execute the function "batch_and_learn"? Wouldn't the algorithm run slower because the GIL of python?
Hope for your answer. Thank you.
Best regards.

**Comment by daochenzha** [comment]
@huzhoudaxia It is a very good question. My understanding is as follows. "batch_and_learn" consists of two parts, including loading training data, and training the models, where most of the computations are performed on GPUs. Multi-threading allows loading the data and do training in parallel so that we can more efficiently make use of the resources. To my knowledge, GIL is for CPU computation but will not restrict GPU. Please correct me if my understanding is wrong. I haven't tried training without multi-threading and they could have similar efficiency.

**Comment by huzhoudaxia** [comment]
@daochenzha I get your point. Thank you.
